development:
  adapter: postgresql
  encoding: unicode
  database: pizzahousemanager_development
  pool: 5
  username: postgres
  password: Kopalnia1

test:
  adapter: postgresql
  encoding: unicode
  database: pizzahousemanager_test
  pool: 5
  username: postgres
  password: Kopalnia1

production:
  adapter: postgresql
  encoding: unicode
  database: pizzahousemanager_production
  pool: 5
  username: postgres
  password: Kopalnia1